name: expense-tracker-webapp
services:
- name: web
  source_dir: /
  github:
    repo: lbanchero/expenses-tracker-webapp
    branch: main
  run_command: echo "Static site - no build needed"
  environment_slug: html
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  static_sites:
  - name: expense-tracker
    source_dir: /
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    output_dir: /
envs:
- key: NODE_ENV
  value: production
- key: SUPABASE_URL
  value: YOUR_SUPABASE_URL
  type: SECRET
- key: SUPABASE_ANON_KEY
  value: YOUR_SUPABASE_ANON_KEY
  type: SECRET
